spring:

  datasource:
     url: jdbc:postgresql://35.158.118.182:5432/postgres
     username: teamuser
     password: teampass
     driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#app:
#  security:
#    jwt:
#      secret_key: "java"
#      expiration: 900
#      refreshExpiration: 604800

server:
  port: 1919
  error:
    include-message: always
logging:
  file:
    name: /home/ec2-user/app.log

  level:
    root: info